spring.application.name=airbnb

# environment variables configuration
spring.config.import=optional:file:.env[.properties]

# database configuration
spring.datasource.url=${DB_URI}

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# devtools configuratiobn
spring.devtools.restart.enabled=true
spring.devtools.restart.exclude=static/**

# logging configuration
logging.level.root=INFO
logging.level.com.example.prod_ready_features.services=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %m%n

# actuator configuration
management.endpoints.web.exposure.include=*